Repository andela/apollo-ah-backend, pull requests merged in 2019-03, with the labels that each got.

#7 #164198172 Setup DB engine configuration with PostgresSQL
  .env.example
  .gitignore
  .sequelizerc
  .travis.yml
  bin/babel-hook
  config/database.js
  database/migrations/.gitkeep
  database/seeders/.gitkeep
  helpers/utils.js
  models/index.js
  package.json
  test/mocha.opts
  test/setup.js
  test/unit/index.test.js
Labels: ready

#8 #164271861 Setup babel
  .babelrc
  package-lock.json
  package.json
Labels: ready, under-review

#11 #164198175 Automate heroku deploy with travisCI
  .travis.yml
Labels: ready

#10 #164276217 Setup Morgan/Winston for logging
  helpers/logger.js
  index.js
  models/User.js
  package.json
  test/unit/index.test.js
  test/unit/logger.test.js
Labels: ready

#16 #164198179 Add user model, migrations and seeders
  .env.example
  .gitignore
  .travis.yml
  bin/babel-hook
  bin/www.js
  database/migrations/.gitkeep
  database/migrations/20190304154730-create-user.js
  database/seeders/.gitkeep
  database/seeders/20190304163942-users-seeders.js
  helpers/utils.js
  index.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  routes/api/index.js
  routes/api/users.js
  routes/index.js
  test/mocha.opts
Labels: ready

#17 #164198179 Implement user authentication with JWT
  .eslintrc.json
  .travis.yml
  Procfile
  bin/babel-hook
  bin/www.js
  config/index.js
  config/passport.js
  controllers/users.js
  middlewares/authenticate.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  routes/index.js
  routes/users.js
  test/integrations/routes/users.test.js
  test/unit/middlewares/authenticate.test.js
Labels: ready

#18 #164198181 Validates signup parameters
  controllers/users.js
  helpers/constants.js
  helpers/responseHelper.js
  index.js
  middlewares/handleValidation.js
  middlewares/validator.js
  package-lock.json
  package.json
  routes/users.js
  test/integrations/routes/users.test.js
  test/unit/index.test.js
  test/unit/logger.test.js
  test/unit/middlewares/authenticate.test.js
Labels: ready

#20 Feat/164198180/signup email
  .env.example
  .travis.yml
  controllers/users.js
  database/migrations/20190304154730-create-user.js
  helpers/constants.js
  helpers/sendMail.js
  models/User.js
  package.json
  routes/users.js
  test/integrations/routes/users.test.js
  views/email/signup.hbs
Labels: ready

#19 #164198184 User should create a profile
  .travis.yml
  bin/babel-hook
  bin/www.js
  controllers/profileController.js
  database/migrations/20190304154730-create-user.js
  database/migrations/20190304173339-create-profile.js
  helpers/constants.js
  helpers/regex.js
  index.js
  middlewares/index.js
  middlewares/validateCreateProfile.js
  models/Profile.js
  models/User.js
  models/index.js
  package.json
  routes/index.js
  routes/profile.js
  seeders/seeders.js
  test/integrations/routes/index.test.js
  test/integrations/routes/profile.test.js
  test/integrations/routes/users.test.js
  test/unit/middlewares/authenticate.test.js
Labels: ready

#23 #164198185 delivers creating articles feature
  controllers/articlesController.js
  database/migrations/20190305135521-create-articles.js
  helpers/articleHelpers.js
  middlewares/articlesMiddleware.js
  models/Article.js
  models/User.js
  models/index.js
  package.json
  routes/articles.js
  routes/index.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/index.test.js
  test/integrations/routes/profile.test.js
  test/integrations/routes/users.test.js
  test/unit/middlewares/articlesMiddleware.test.js
Labels: ready

#25 Bg/164531637/articletest emailenv bug
  helpers/sendMail.js
  routes/users.js
  test/integrations/routes/articles.test.js
  test/unit/sendMail.js
Labels: ready, under-review

#24 #164198183 Social authentication
  .env.example
  auth/passport.js
  controllers/authController.js
  index.js
  package.json
  routes/auth.js
  routes/index.js
  test/integrations/routes/auth.test.js
  test/unit/middlewares/socialAuth.test.js
Labels: ready

#27 #164198188 Users should be able to like and dislike article
  .travis.yml
  controllers/articleLikesController.js
  controllers/articlesController.js
  controllers/profileController.js
  database/migrations/20190304154730-create-user.js
  database/migrations/20190304173339-create-profile.js
  database/migrations/20190305135521-create-articles.js
  database/migrations/20190310125003-create-like-article.js
  helpers/utils.js
  middlewares/articlesMiddleware.js
  middlewares/authenticate.js
  middlewares/validateCreateProfile.js
  models/Article.js
  models/ArticleLikes.js
  models/Profile.js
  models/index.js
  package.json
  routes/articles.js
  routes/index.js
  routes/profile.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/index.test.js
  test/integrations/routes/profile.test.js
  test/integrations/routes/users.test.js
  test/unit/middlewares/articlesMiddleware.test.js
  test/unit/sendMail.test.js
  views/email/password.hbs
  views/email/signup.hbs
Labels: ready

#30 Feature/164569040/user settings
  controllers/settingsController.js
  controllers/users.js
  database/migrations/20190312152110-create-settings.js
  middlewares/handleValidation.js
  middlewares/validator.js
  models/Setting.js
  models/index.js
  routes/index.js
  routes/settings.js
  test/integrations/routes/settings.test.js
  test/unit/middlewares/socialAuth.test.js
  test/unit/models/settings.test.js
Labels: under-review

#31 #164521891 Implements reset password
  .env.example
  controllers/usersController.js
  helpers/constants.js
  middlewares/tokenizer.js
  middlewares/validator.js
  package.json
  routes/users.js
  test/integrations/routes/password.test.js
  test/mocha.opts
Labels: ready

#32 #164198196 Article read time
  controllers/articlesController.js
  database/migrations/20190305135521-create-articles.js
  helpers/articleHelpers.js
  middlewares/authenticate.js
  models/Article.js
  test/unit/middlewares/articlesMiddleware.test.js
  test/unit/middlewares/socialAuth.test.js
Labels: ready, under-review

#28 #164198189 Add support for users to be able to follow other users
  controllers/followersController.js
  controllers/profileController.js
  controllers/settingsController.js
  controllers/usersController.js
  database/migrations/20190304154730-create-user.js
  database/migrations/20190304173339-create-profile.js
  database/migrations/20190305135521-create-articles.js
  database/migrations/20190310125003-create-like-article.js
  database/migrations/20190312152110-create-settings.js
  database/migrations/20190313024339-create-users-followers.js
  database/seeders/20190304163942-users-seeders.js
  helpers/constants.js
  index.js
  middlewares/exceptionHandler.js
  models/Article.js
  models/ArticleLikes.js
  models/Profile.js
  models/Setting.js
  models/User.js
  models/UserFollowers.js
  models/index.js
  package.json
  routes/auth.js
  routes/profile.js
  test/helpers/index.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/home.test.js
  test/integrations/routes/profile.test.js
  test/integrations/routes/settings.test.js
  test/integrations/routes/users.test.js
  test/setup.js
  test/unit/middlewares/articlesMiddleware.test.js
  test/unit/models/profiles.test.js
  test/unit/models/settings.test.js
Labels: ready

#34 #164198185: delivers read, update, delete articles
  controllers/articlesController.js
  controllers/usersController.js
  middlewares/articlesMiddleware.js
  package.json
  routes/articles.js
  routes/index.js
  routes/profile.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/profile.test.js
  test/unit/middlewares/articlesMiddleware.test.js
Labels: ready

#33 #164198194 Users should be able to view user profiles
  controllers/articlesController.js
  controllers/profileController.js
  database/migrations/20190314053802-change-username-constraints.js
  package.json
  routes/profile.js
  seeders/seeders.js
  test/helpers/testData.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/profile.test.js
  test/integrations/routes/users.test.js
Labels: ready

#37 #164198193 Implements pagination for articles
  controllers/articlesController.js
  helpers/articleHelpers.js
  helpers/constants.js
  middlewares/articlesMiddleware.js
  middlewares/validator.js
  routes/articles.js
  test/integrations/routes/articles.test.js
Labels: ready

#35 #164599833 user notification
  bin/www.js
  controllers/notificationsController.js
  controllers/usersController.js
  database/migrations/20190313141157-create-notifications.js
  index.js
  models/Notification.js
  models/index.js
  package.json
  routes/index.js
  routes/notifications.js
  routes/users.js
  test/integrations/routes/notification.test.js
  test/unit/notifications.test.js
  views/email/notification.hbs
Labels: ready

#36 #164198192: Add support for tagging articles
  controllers/articlesController.js
  controllers/tagsController.js
  database/migrations/20190305135521-create-articles.js
  database/migrations/20190314024638-create-tag.js
  database/migrations/20190315203736-create-article-tag.js
  database/seeders/20190304163942-users-seeders.js
  database/seeders/20190314025327-tags-seeders.js.js
  database/seeders/20190314224323-article-seeders.js
  middlewares/articlesMiddleware.js
  models/Article.js
  models/ArticleTag.js
  models/Tag.js
  models/User.js
  routes/articles.js
  routes/index.js
  routes/tags.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/tags.test.js
  test/integrations/routes/users.test.js
Labels: ready

#38 #164198198 Users can bookmark articles
  controllers/articlesController.js
  database/migrations/20190316155818-create-bookmark.js
  models/Article.js
  models/Bookmark.js
  models/User.js
  routes/articles.js
  routes/bookmarks.js
  routes/index.js
  test/helpers/testData.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/bookmark.test.js
Labels: ready

#41 #164198187 implement commenting on articles feature
  controllers/articlesController.js
  controllers/commentsController.js
  database/migrations/20190315122058-create-comment.js
  helpers/articleHelpers.js
  middlewares/articlesMiddleware.js
  middlewares/commentsMiddleware.js
  models/Comment.js
  models/User.js
  routes/articles.js
  routes/comments.js
  routes/index.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/comments.test.js
  test/unit/middlewares/comments.test.js
Labels: ready

#42 #164691492 Authors can select category for an article
  .travis.yml
  controllers/articlesController.js
  database/migrations/20190318132023-create-category.js
  database/migrations/20190318134144-add-categories.js
  database/seeders/categorySeed/20190318141410-category-seeders.js
  helpers/articleHelpers.js
  middlewares/articlesMiddleware.js
  models/Article.js
  models/ArticleCategory.js
  package.json
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/bookmark.test.js
  test/integrations/routes/comments.test.js
  test/integrations/routes/tags.test.js
  test/setup.js
  test/unit/middlewares/articlesMiddleware.test.js
  test/unit/middlewares/comments.test.js
Labels: ready

#43 #164198195 Implement search and filter
  controllers/articlesController.js
  database/migrations/20190321070613-add-indexes.js
  helpers/articleHelpers.js
  helpers/constants.js
  middlewares/articlesMiddleware.js
  middlewares/handleValidation.js
  middlewares/validator.js
  package.json
  routes/articles.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/search.test.js
  test/mocha.opts
  test/setup.js
Labels: ready

#45 feat(stats): implements user statistics
  .env.example
  controllers/articlesController.js
  controllers/statsController.js
  database/migrations/20190320080157-create-history.js
  helpers/statsHelper.js
  index.js
  middlewares/articlesMiddleware.js
  middlewares/statsMiddleware.js
  models/Article.js
  models/History.js
  models/User.js
  routes/articles.js
  routes/index.js
  routes/stats.js
  test/integrations/routes/articles.test.js
  test/integrations/routes/stats.test.js
  test/unit/middlewares/stats.test.js
Labels: ready

#44 #164198204/comment history
  controllers/commentsController.js
  database/migrations/20190320121330-create-comment-history.js
  models/Comment.js
  models/CommentHistory.js
  test/integrations/routes/comments.test.js
Labels: under-review

#40 #164198186 Implement article rating feature
  .env.example
  controllers/articleRatingController.js
  controllers/articlesController.js
  database/migrations/20190317233511-create-ratings.js
  database/seeders/20190314224323-article-seeders.js
  helpers/articleRatingHelper.js
  middlewares/ratings.js
  models/Article.js
  models/Ratings.js
  models/index.js
  routes/index.js
  routes/ratings.js
  test/integrations/routes/articleRating.test.js
  test/integrations/routes/auth.test.js
Labels: ready

#48 #164198199 Report article
  controllers/articleRatingController.js
  controllers/reportArticleController.js
  database/migrations/20190319074517-create-report.js
  middlewares/index.js
  middlewares/validateReport.js
  models/Report.js
  routes/index.js
  routes/reportArticle.js
  test/integrations/routes/bookmark.test.js
  test/integrations/routes/reportArticle.test.js
Labels: ready

#47 #164198202 Add support for Role Based Access Control (RBAC)
  controllers/rolesController.js
  controllers/usersController.js
  database/migrations/20190320080022-create-role.js
  database/migrations/20190321213819-create-permission.js
  database/migrations/20190322020500-create-user-role.js
  database/migrations/20190322035846-create-role-permissions.js
  database/seeders/20190304163942-users-seeders.js
  database/seeders/20190318141410-category-seeders.js
  database/seeders/20190322021156-roles-seeders.js
  helpers/constants.js
  middlewares/index.js
  middlewares/permission.js
  middlewares/validator.js
  models/Permission.js
  models/Role.js
  models/User.js
  package.json
  routes/index.js
  routes/roles.js
  test/helpers/testData.js
  test/integrations/routes/articleLikes.test.js
  test/integrations/routes/articleRating.test.js
  test/integrations/routes/roles.test.js
  test/setup.js
Labels: ready

#49 #164198200 Users should be able to like and unlike comments
  controllers/commentLikesController.js
  controllers/profileController.js
  database/migrations/20190320131709-create-comment-likes.js
  helpers/constants.js
  middlewares/authenticate.js
  middlewares/handleValidation.js
  middlewares/index.js
  middlewares/validateCreateProfile.js
  middlewares/validator.js
  models/ArticleLikes.js
  models/Comment.js
  models/CommentLikes.js
  models/User.js
  package.json
  routes/comments.js
  routes/profile.js
  test/integrations/routes/comments.test.js
  test/integrations/routes/profile.test.js
Labels: ready

#51 #164859695 - Minimal code refactor on article reporting
  .env.example
  test/integrations/routes/reportArticle.test.js
  test/unit/middlewares/articlesMiddleware.test.js
Labels: ready

#50 #164859311 update readme file
  README.md
  database/seeders/20190218141410-category-seeders.js
Labels: ready

#52 #164866970 Prepare app for babel build
  .babelrc
  .gitignore
  .travis.yml
  Procfile
  index.js
  package.json
Labels: ready
